### ISSUE TITLE
Multilevel menu ...

### ISSUE THREAD

**Issue by hackthenet** [ramiz4/ngx-multi-level-push-menu#31]
I cant , or i have understand as i can push a sub menu level using multiLevelPushMenu and  multiLevelPushMenu.

How i can do it .... like old jquery version ..
http://multi-level-push-menu.make.rs/demo/basicjs/basicjs.html

Thanks

**Comment by jacobbullock** [comment]
@hackthenet did you ever get this working?  I don't see anything in here that actually supports multi level menus.  The example code doesn't appear to work with multi levels

**Comment by ramiz4** [comment]
i fixed it in Version 1.5.13
Follow the description in step three... how to create multi-level menu (example company with submenus contact and imprint)
https://www.npmjs.com/package/@ramiz4/ngx-multi-level-push-menu/v/1.5.13#3-add-menu-options-and-items-to-appcomponentts-
