### ISSUE TITLE
Cannot find module '@ramiz4/ngx-multi-level-push-menu' version 1.5.14

### ISSUE THREAD

**Issue by Ianc22** [ramiz4/ngx-multi-level-push-menu#56]
Hi,

There seems to be a problem with the package. I've tried updating from version 1.5.11, and I've also created a clean project and installed v1.5.14 but I get get the same error on a clean install...

Can you check it out, please?

Thanks

**Comment by ramiz4** [comment]
Which angular version do you use?

**Comment by Ianc22** [comment]
Hey, currently V5. I also created a new app (V6) using the CLI to test it out but got the same error.

**Comment by ramiz4** [comment]
Unfortunately, the package is currently only compatible with Angular Version 4

**Comment by ramiz4** [comment]
I will upgrade the package to version 6 soon and make it available for Angular 6

**Comment by Ianc22** [comment]
Ahh OK, guess I'll just stick with 1.5.11 as that works fine with Angular V5 😉
